#!/bin/sh

set -e

if [ "$1" = "upgrade" ]; then
    systemctl stop greenboot-healthcheck.service
    systemctl stop greenboot-loading-message.service
    systemctl stop greenboot-task-runner.service
    systemctl stop redboot-task-runner.service
    systemctl stop redboot.target
    systemctl stop greenboot-status.service
    systemctl stop greenboot-grub2-set-counter.service
    systemctl stop greenboot-grub2-set-success.service
    systemctl stop greenboot-rpm-ostree-grub2-check-fallback.service
    systemctl stop redboot-auto-reboot.service
fi

exit 0
